// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Healthcheck
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Delete level by id
	// (POST /levels/finish)
	FinishLevel(w http.ResponseWriter, r *http.Request)
	// Get hint for level
	// (POST /levels/hint)
	PostLevelsHint(w http.ResponseWriter, r *http.Request)
	// Generate a new level
	// (POST /levels/start)
	PostLevelsStart(w http.ResponseWriter, r *http.Request)
	// Get level by id
	// (GET /levels/{levelId})
	GetLevel(w http.ResponseWriter, r *http.Request, levelId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Healthcheck
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete level by id
// (POST /levels/finish)
func (_ Unimplemented) FinishLevel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get hint for level
// (POST /levels/hint)
func (_ Unimplemented) PostLevelsHint(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate a new level
// (POST /levels/start)
func (_ Unimplemented) PostLevelsStart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get level by id
// (GET /levels/{levelId})
func (_ Unimplemented) GetLevel(w http.ResponseWriter, r *http.Request, levelId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FinishLevel operation middleware
func (siw *ServerInterfaceWrapper) FinishLevel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FinishLevel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLevelsHint operation middleware
func (siw *ServerInterfaceWrapper) PostLevelsHint(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLevelsHint(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLevelsStart operation middleware
func (siw *ServerInterfaceWrapper) PostLevelsStart(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLevelsStart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLevel operation middleware
func (siw *ServerInterfaceWrapper) GetLevel(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "levelId" -------------
	var levelId string

	err = runtime.BindStyledParameterWithOptions("simple", "levelId", chi.URLParam(r, "levelId"), &levelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "levelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLevel(w, r, levelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/levels/finish", wrapper.FinishLevel)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/levels/hint", wrapper.PostLevelsHint)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/levels/start", wrapper.PostLevelsStart)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/levels/{levelId}", wrapper.GetLevel)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8yX227bOBPHX4Xg910qkbyOc9Bd99A02GBb1ItdYItcMNLYYiseSo6SGIHffUFSsiWb",
	"iovAAfZOCQ8z85v/DMfPtFBCKwkSLc2fqS0qEMx//maMMp/BaiUtuH9oozQY5OCXBVjLln4BVxpoTi0a",
	"Lpd0vU6oge8NN1DS/Mtm413SbVT3X6FAuk7oey65rW7hAerP8L0Bi/uGard6Ux421G2MGbpmAv5gwrsL",
	"shFu/yNDMFYZ7J3ork7oB2A1VuPxW2TY+C94YkLX3t43mhxwsj0W8/EDl/gKCklYmyND7+b/DSxoTv+X",
	"bjObtmlNb7c7x+gNrht3cwxLxaX3vuS2MFxwyVAZrxemtfM3f+6BH3Hzb7dhrgw6W85ma2MVUkiXXTbX",
	"CVUSPi5o/uXlwHdujMXF7bwpCrC2x/heqRqY3IO13Ru7qdXzGCJeDlVzNoVLmML5CZuW2cnZZHFxcjWb",
	"nJ9cXU5ns/NZeXF1dUEjChVczhF0qEYuuXCyzjYbuURYgnE7LTKDt69SSdIXels4Eh5pQjXI0nniyLBy",
	"RRPKZaGMcRDuDpUBd0Jrb973bxTqxv3jyGsY6PFE1r83Fst8E+9ovS97Deslm5vGtkt4c0HMgb84q72Z",
	"EhxHjVxJmtN3xrAVUQvy4NYTAqyo/DfhljBJWLdeqFoZSxZGCXKvEJUgqAgq7VSAIILOuw/BnoI4J7Nk",
	"q9RJTKntf7yh2N/DOj4CtYS6+G5kCU/vjRK92u95tdnyp4pt2CE/vHB4Onk5LzEF7QUZ4P+imkAgTncW",
	"o/taPPbQgaCnUQl2t+yH7I5wuQhYOfp++A+ruW5qTt59unFHwdggz+x0cpr5ctQgmeY0p9PT7HTqmhHD",
	"ynuZVv7d9mIAz8ehY07g7vWk14DhZfd9K7Rof/CnLAtwJUIAy7SueeGPpl+t86Cbjw7h2JkdfJTDSvv4",
	"u6dlGyGYWdG8HTeKCopvfiX1r7BNF35C8iJQNhJPb4KigT5Y/FmVq6MFE5nR1uuQ6gG+s/1+4g+REmpA",
	"KF3izsKuo/g1nE8jjIN1qZAsVCPLHeC/eq+Ix0zuV4SXA+7dHBOn/knZUKLW96G3Ad+fB6PEsyObGkfp",
	"1qMUrwFJFRZNYDmg6B/2H8HoX8Q34rj/2kZpTo5mcDj/jSqzMMDaupgdMZcH6+JGIhjJamLBPIAh4A7s",
	"5VW6RAFhRMJjJLPP7e+F9UudtmtLmhkmwE1lfobizgvXsWlCZRi2tr8+tg8ImgaSXtC7E+XdGxbED6aw",
	"LYn/VGNzJTnsam7Zpzrgb0xNc1oh6jxNa1WwulIW88vsMkvp+m79bwAAAP//F7Yv6hQQAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
